### ISSUE TITLE
Readme needs updating

### ISSUE THREAD

**Issue by neilgupta** [Crimsonninja/incorporation-validator#1]
You should update the readme to include why this repo exists, and more importantly, why I'm a collaborator on it 🤔

**Comment by Crimsonninja** [comment]
Yo I totally forgot about this. What was this app even?? Hahaaaa

**Comment by Crimsonninja** [comment]
Think I remember now! 😃

**Comment by neilgupta** [comment]
oh wow I totally forgot about Found... apparently 2015 me also forgot about it, based on my last commit message 😅 

https://github.com/Undesigned/foundation/commit/5c6c0b8fe5ce1bb0483c83b2dd14e9f78417c47f

nice sleuthing!
